In [61]:
from sklearn.cross_decomposition import CCA
import numpy as np
from scipy import stats
np.random.seed(1)

In [62]:
def create_view_matrices(mix = True, size = (25, 3)):
    
    # noise for X and Y
                         
    noise_X = 0.1 * (np.random.rand(*size) - 0.5)
    noise_Y = 0.1 * (np.random.rand(*size) - 0.5)
    
    # scale each data point
                         
    scale = np.zeros(size)
    for i in range(size[1]):
        scale[:, i] = np.arange(size[0])
    
    # create scaled and noised X and Y
    

    X = scale * (np.ones(size) + noise_X)
    Y = -2 * (scale * (np.ones(size) + noise_Y))
    
    # put pure noise in the last column of X
    print(X.shape)
    #noise_column = np.random.rand(size[0])
    #X[:, 2] = noise_column
                         
    if mix:
                         
        mix_matrix = np.random.rand(size[1], size[1]) - 0.5
        X = X.dot(mix_matrix)
        Y = Y.dot(mix_matrix)
        
    return X,Y

def run_CCA(X, Y, n_components = 3):
                         
    cca = CCA(n_components = n_components)
    cca.fit(X, Y)
    X_transformed, Y_transformed = cca.transform(X, Y)
    X_weights, Y_weights = np.round(cca.x_weights_, decimals = 4), np.round(cca.y_weights_, decimals = 4)
                         
    return (X_transformed, Y_transformed), (X_weights, Y_weights)

In [65]:
n_components = 3
X, Y = create_view_matrices(mix = True)

print("X is")
print(X)
print("=============================")
print("Y is")
print(Y)
print("=============================")
(X_transformed, Y_transformed), (X_weights, Y_weights) = run_CCA(X, Y, n_components=n_components)

print(X_transformed)
print("===========================")
print(Y_transformed)
print("===========================")

for dim in range(n_components):
    corrcoef, p_value = stats.pearsonr(X_transformed[:, dim], Y_transformed[:, dim])
    print(corrcoef)

(25, 3)
X is
[[  0.           0.           0.        ]
 [ -0.84169913  -0.13022595   0.38549475]
 [ -1.74344655  -0.30655445   0.82485801]
 [ -2.61536738  -0.40976463   1.2109409 ]
 [ -3.42421769  -0.60477049   1.61110514]
 [ -4.31160903  -0.75324189   2.03105035]
 [ -5.26585234  -0.79238846   2.39972164]
 [ -6.02841081  -0.977472     2.81217205]
 [ -6.96681103  -1.3146604    3.35355099]
 [ -7.94839999  -1.07374263   3.57032893]
 [ -8.91914341  -1.22232471   4.00741505]
 [ -9.73232687  -1.91348426   4.72126065]
 [-10.60089389  -1.66877442   4.88387778]
 [-11.27950331  -1.57589385   5.02511236]
 [-12.09136191  -2.08182405   5.65017388]
 [-13.10496581  -1.81362591   5.85925182]
 [-14.18733741  -1.83651057   6.30770332]
 [-14.58020137  -1.6736899    6.31274153]
 [-16.0182551   -2.52016643   7.40876926]
 [-16.86150649  -2.89625734   7.87800996]
 [-16.86427503  -2.78818922   7.86786984]
 [-18.01550099  -3.13632195   8.5368934 ]
 [-19.38815586  -2.81588763   8.82710817]
 [-19.85653953  -3.14